["CC0-1.0.txt"]
url = "https://raw.githubusercontent.com/maxwell-k/dotlocalslashbin/refs/tags/v0.0.12/LICENSES/CC0-1.0.txt"
expected = "a2010f343487d3f7618affe54f789f5487602331c0a8d03f49e9a7c547cf0499"

# examples/2.toml
# SPDX-FileCopyrightText: 2025 Keith Maxwell <keith.maxwell@gmail.com>
# SPDX-License-Identifier: CC0-1.0
